-- =============================================================================
-- Migration: 003_create_payment_links
-- Creates the PaymentLink entity.
-- See docs/DATA_MODEL.md §1 (PaymentLink) and §2 (transaction state machine).
-- =============================================================================

CREATE TABLE payment_links (
    link_id             UUID            PRIMARY KEY DEFAULT gen_random_uuid(),
    -- link_id is also the token embedded in the URL shared with the buyer.
    -- UUIDs are not guessable, but the checkout page should also enforce expiry.

    merchant_id         UUID            NOT NULL REFERENCES merchants(merchant_id),

    -- Integer, smallest currency unit (kobo). NEVER a float (Engineering Rule 6).
    amount_minor_units  BIGINT          NOT NULL CHECK (amount_minor_units > 0),
    currency            TEXT            NOT NULL DEFAULT 'NGN',

    -- Item description as entered by the merchant in the ConFam thread.
    description         TEXT            NOT NULL,

    -- State machine: created → opened → paid → settling → logged
    --                                  ↓                   ↓
    --                               expired              failed
    -- See docs/DATA_MODEL.md §2 for full semantics.
    status              TEXT            NOT NULL DEFAULT 'created',
    CONSTRAINT payment_links_status_check CHECK (
        status IN ('created', 'opened', 'paid', 'settling', 'logged', 'expired', 'failed')
    ),

    expires_at          TIMESTAMPTZ     NOT NULL,
    created_at          TIMESTAMPTZ     NOT NULL DEFAULT now()
);

COMMENT ON TABLE payment_links IS
    'One-time payment links generated by merchants in the ConFam thread. '
    'link_id is the URL token. amount_minor_units is BIGINT kobo — never float (Rule 6). '
    'A link must not be reusable: status transitions to logged or expired are terminal.';

COMMENT ON COLUMN payment_links.amount_minor_units IS
    'Amount in the smallest currency unit (kobo for NGN). '
    'BIGINT enforces no-float at the schema level (Engineering Rule 6).';
