"""
Alembic environment configuration for ConFam.

Migration approach: raw SQL (not autogenerate from ORM models).
Reason: the ledger schema requires precise DDL control — triggers, RULEs,
column-level GRANTs — that ORM-autogenerated migrations cannot produce
correctly. Engineering Rules 2 and 6 depend on the exact SQL being right.

How migrations work here:
  - Each revision in alembic/versions/ calls op.execute() with raw SQL
    sourced from db/migrations/*.sql (or inline for small changes).
  - The Alembic version table tracks which migrations have been applied.
  - `alembic upgrade head` applies all pending migrations in order.

Connection: uses ALEMBIC_DATABASE_URL from environment (confam_migrator role).
The running application uses DATABASE_URL (confam_app role) — never the same.
See db/migrations/007_create_roles_and_grants.sql and .env.example.
"""

import os
from logging.config import fileConfig

from sqlalchemy import engine_from_config, pool

from alembic import context

# Alembic Config object — provides access to alembic.ini values.
config = context.config

# Resolve the database URL from environment.
# ALEMBIC_DATABASE_URL must be set before running any alembic command.
# It should connect as confam_migrator, not confam_app.
alembic_db_url = os.environ.get("ALEMBIC_DATABASE_URL")
if not alembic_db_url:
    raise RuntimeError(
        "ALEMBIC_DATABASE_URL environment variable is not set. "
        "Copy .env.example to .env and set ALEMBIC_DATABASE_URL to a "
        "confam_migrator connection string before running Alembic. "
        "See db/migrations/007_create_roles_and_grants.sql."
    )
config.set_main_option("sqlalchemy.url", alembic_db_url)

# Set up Python logging from alembic.ini config.
if config.config_file_name is not None:
    fileConfig(config.config_file_name)

# No MetaData target — we use raw SQL migrations, not autogenerate.
target_metadata = None


def run_migrations_offline() -> None:
    """Run migrations in 'offline' mode (emit SQL to stdout, no DB connection)."""
    url = config.get_main_option("sqlalchemy.url")
    context.configure(
        url=url,
        target_metadata=target_metadata,
        literal_binds=True,
        dialect_opts={"paramstyle": "named"},
    )
    with context.begin_transaction():
        context.run_migrations()


def run_migrations_online() -> None:
    """Run migrations in 'online' mode (applies to a live database connection)."""
    connectable = engine_from_config(
        config.get_section(config.config_ini_section, {}),
        prefix="sqlalchemy.",
        poolclass=pool.NullPool,
    )
    with connectable.connect() as connection:
        context.configure(
            connection=connection,
            target_metadata=target_metadata,
        )
        with context.begin_transaction():
            context.run_migrations()


if context.is_offline_mode():
    run_migrations_offline()
else:
    run_migrations_online()
